// Code generated by go-swagger; DO NOT EDIT.

package home

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injapi/models"
)

// HomeOKCode is the HTTP code returned for type HomeOK
const HomeOKCode int = 200

/*HomeOK 登录成功，返回登录信息

swagger:response homeOK
*/
type HomeOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse200 `json:"body,omitempty"`
}

// NewHomeOK creates HomeOK with default headers values
func NewHomeOK() *HomeOK {
	return &HomeOK{}
}

// WithPayload adds the payload to the home o k response
func (o *HomeOK) WithPayload(payload *models.InlineResponse200) *HomeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the home o k response
func (o *HomeOK) SetPayload(payload *models.InlineResponse200) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HomeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrHomeDefault error

swagger:response homeDefault
*/
type NrHomeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrHomeDefault creates NrHomeDefault with default headers values
func NewNrHomeDefault(code int) *NrHomeDefault {
	if code <= 0 {
		code = 500
	}

	return &NrHomeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the home default response
func (o *NrHomeDefault) WithStatusCode(code int) *NrHomeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the home default response
func (o *NrHomeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the home default response
func (o *NrHomeDefault) WithPayload(payload *models.Error) *NrHomeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the home default response
func (o *NrHomeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrHomeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
