// Code generated by go-swagger; DO NOT EDIT.

package praise

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrPraiseListHandlerFunc turns a function with the right signature into a praise list handler
type NrPraiseListHandlerFunc func(NrPraiseListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrPraiseListHandlerFunc) Handle(params NrPraiseListParams) middleware.Responder {
	return fn(params)
}

// NrPraiseListHandler interface for that can handle valid praise list params
type NrPraiseListHandler interface {
	Handle(NrPraiseListParams) middleware.Responder
}

// NewNrPraiseList creates a new http.Handler for the praise list operation
func NewNrPraiseList(ctx *middleware.Context, handler NrPraiseListHandler) *NrPraiseList {
	return &NrPraiseList{Context: ctx, Handler: handler}
}

/*NrPraiseList swagger:route GET /praise/list Praise praiseList

点赞列表

点赞列表

*/
type NrPraiseList struct {
	Context *middleware.Context
	Handler NrPraiseListHandler
}

func (o *NrPraiseList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrPraiseListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
