// Code generated by go-swagger; DO NOT EDIT.

package praise

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injapi/models"
)

// PraiseListOKCode is the HTTP code returned for type PraiseListOK
const PraiseListOKCode int = 200

/*PraiseListOK 查询成功

swagger:response praiseListOK
*/
type PraiseListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20012 `json:"body,omitempty"`
}

// NewPraiseListOK creates PraiseListOK with default headers values
func NewPraiseListOK() *PraiseListOK {
	return &PraiseListOK{}
}

// WithPayload adds the payload to the praise list o k response
func (o *PraiseListOK) WithPayload(payload *models.InlineResponse20012) *PraiseListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the praise list o k response
func (o *PraiseListOK) SetPayload(payload *models.InlineResponse20012) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PraiseListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
