// Code generated by go-swagger; DO NOT EDIT.

package spare

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "injapi/models"
)

// SpareListOKCode is the HTTP code returned for type SpareListOK
const SpareListOKCode int = 200

/*SpareListOK 查询成功

swagger:response spareListOK
*/
type SpareListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20013 `json:"body,omitempty"`
}

// NewSpareListOK creates SpareListOK with default headers values
func NewSpareListOK() *SpareListOK {
	return &SpareListOK{}
}

// WithPayload adds the payload to the spare list o k response
func (o *SpareListOK) WithPayload(payload *models.InlineResponse20013) *SpareListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the spare list o k response
func (o *SpareListOK) SetPayload(payload *models.InlineResponse20013) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SpareListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
