// Code generated by go-swagger; DO NOT EDIT.

package spare

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// NrSpareClickURL generates an URL for the spare click operation
type NrSpareClickURL struct {
	ActivityID     *int64
	MemberID       *int64
	TargetMemberID *int64
	Value          *float64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *NrSpareClickURL) WithBasePath(bp string) *NrSpareClickURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *NrSpareClickURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *NrSpareClickURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/spare/click"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/joe9724/jinlinonline/1.0.0"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var activityID string
	if o.ActivityID != nil {
		activityID = swag.FormatInt64(*o.ActivityID)
	}
	if activityID != "" {
		qs.Set("activityId", activityID)
	}

	var memberID string
	if o.MemberID != nil {
		memberID = swag.FormatInt64(*o.MemberID)
	}
	if memberID != "" {
		qs.Set("memberId", memberID)
	}

	var targetMemberID string
	if o.TargetMemberID != nil {
		targetMemberID = swag.FormatInt64(*o.TargetMemberID)
	}
	if targetMemberID != "" {
		qs.Set("targetMemberId", targetMemberID)
	}

	var value string
	if o.Value != nil {
		value = swag.FormatFloat64(*o.Value)
	}
	if value != "" {
		qs.Set("value", value)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *NrSpareClickURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *NrSpareClickURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *NrSpareClickURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on NrSpareClickURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on NrSpareClickURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *NrSpareClickURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
