// Code generated by go-swagger; DO NOT EDIT.

package spare

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrSpareClickHandlerFunc turns a function with the right signature into a spare click handler
type NrSpareClickHandlerFunc func(NrSpareClickParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrSpareClickHandlerFunc) Handle(params NrSpareClickParams) middleware.Responder {
	return fn(params)
}

// NrSpareClickHandler interface for that can handle valid spare click params
type NrSpareClickHandler interface {
	Handle(NrSpareClickParams) middleware.Responder
}

// NewNrSpareClick creates a new http.Handler for the spare click operation
func NewNrSpareClick(ctx *middleware.Context, handler NrSpareClickHandler) *NrSpareClick {
	return &NrSpareClick{Context: ctx, Handler: handler}
}

/*NrSpareClick swagger:route GET /spare/click Spare spareClick

打赏

打赏

*/
type NrSpareClick struct {
	Context *middleware.Context
	Handler NrSpareClickHandler
}

func (o *NrSpareClick) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrSpareClickParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
