// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Banner 大图
// swagger:model Banner
type Banner struct {

	// cover
	Cover string `json:"cover"`

	// 备用字段
	ExtraInfo1 int64 `json:"extraInfo1,omitempty"`

	// 备用字段
	ExtraInfo2 string `json:"extraInfo2,omitempty"`

	// 备用字段
	ExtraInfo3 string `json:"extraInfo3,omitempty"`

	// 备用字段
	Icon string `json:"icon,omitempty"`

	// id
	ID int64 `json:"id"`

	// order
	Order int64 `json:"order,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`

	// 跳转类型(0=app内任务 1=app内web 2=app外web 3=活动 4=app内圈子 5=app内商品 6=街景 7=站内查公交页)
	Type int64 `json:"type"`

	// url
	URL string `json:"url"`

	Title string `json:"title"`
}

// Validate validates this banner
func (m *Banner) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Banner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Banner) UnmarshalBinary(b []byte) error {
	var res Banner
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
