// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Spare 打赏
// swagger:model Spare
type Spare struct {

	// from
	From int64 `json:"from,omitempty"`

	// shuoshuo Id
	ShuoshuoID int64 `json:"shuoshuoId,omitempty"`

	// time
	Time int64 `json:"time,omitempty"`

	// to
	To int64 `json:"to,omitempty"`

	// topic Id
	TopicID int64 `json:"topicId,omitempty"`

	// 打赏金额
	Value float64 `json:"value,omitempty"`
}

// Validate validates this spare
func (m *Spare) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Spare) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Spare) UnmarshalBinary(b []byte) error {
	var res Spare
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
